config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects do
    resources :tasks do
      member do
        patch :complete
      end
    end
  end

  authenticated :user do
    root to: 'projects#index', as: :authenticated_root
  end

  root to: redirect('/users/sign_in')
  
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project

  def completed?
    !completed_at.blank?
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /projects
  # GET /projects.json
  def index
    @projects = current_user.projects.order('id')
    @project  = Project.new
    @task     = Task.new
  end

  # POST /projects.json
  def create
    @project = current_user.projects.build(name: "New Project")

    respond_to do |format|
      if @project.save
        # format.html { redirect_to projects_url, notice: 'Project was successfully created.' }
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.js   { }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.js   { }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.js   { }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      begin
        @project = current_user.projects.find(params[:id])
      rescue Exception => e
        flash[:notice] = "ERROR"
        redirect_to root_path
        return
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name)
    end
end

app/controllers/tasks_controller.rb
 class TasksController < ApplicationController
  before_action :set_project
  before_action :set_task, except: [:create]
  before_filter :authenticate_user!

  def create
    @task = @project.tasks.create(name: task_params[:name], order: @project.tasks.count)
    
    respond_to do |format|
      if @task.save
        format.html { redirect_to root_path, notice: 'Task was successfully created.' }
        format.js   { }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to root_path, notice: 'Task was successfully updated.' }
        format.js   { }
        format.json { render :show, status: :ok, location: @task }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @task.destroy
        format.html { redirect_to root_path, notice: 'Task was deleted succesfullly.' }
        format.js   { }
        format.json { head :no_content }
      end
    end
  end

  def complete
    respond_to do |format|
      if @task.update_attribute(:completed_at, Time.now)
        format.html { redirect_to root_path, notice: 'Todo item completed.' }
        format.js   { }
      end
    end
  end

  private

  def set_project
    begin
      @project = current_user.projects.find(params[:project_id])
    rescue Exception => e
      flash[:notice] = "ERROR"
      redirect_to root_path
      return
    end
  end

  def set_task
    @task = @project.tasks.find(params[:id])
  end

  def task_params
    params[:task].permit(:name)
  end

end
#     t.string   "name"
#     t.boolean  "status"
#     t.integer  "order"
#     t.integer  "project_id"
#     t.datetime "created_at"
#     t.datetime "updated_at"
#     t.datetime "completed_at"
#     t.datetime "deadline_at"

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RGTodo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

</head>
<body>
  <header class="navbar navbar-default navbar-fixed-top shadow" role="navigation">
    <div class="navbar-inner">
      <nav class="collapse navbar-collapse navbar-ex1-collapse">
        <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Account', edit_user_registration_path %></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav pull-right">
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
          </ul>
        <% end %>
      </nav>
    </div>
  </header>

  <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-info") %>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/projects/_project.html.erb
<div id=<%= "project_#{project.id.to_s}" %> class="container shadow">
  <div class="row clearfix blue-gradient project-header raised outlined">
    <div class="calender col-xs-1">
      <i class="fa fa-calendar"></i>
    </div>
    <div class="project_title col-xs-9">
      <%= form_for project, remote: true do |f| %>
          <%= f.label "#{project.name}", class: 'label_title' %>
          <%= f.text_field :name, class: 'input_title' %>
      <% end %>
    </div>
    <div class="small-buttons col-xs-2 hide">
      <small>
        <%= link_to '', class: "edit-project" do %>
          <i class='fa fa-pencil'></i>
        <% end %>
      </small>
      |
      <small>
        <%= link_to project, method: :delete, data: { confirm: 'Are you sure?'}, remote: true, class: "delete-project" do %>
          <i class='fa fa-trash'></i>
        <% end %>
      </small>
    </div>
  </div>
  <div class="form raised outlined lightgray-gradient">
      <%= form_for([project, Task.new], remote: true, html: { class: "task-form" } ) do |f|%>
        <i class="fa fa-plus col-xs-1 green-gradient-symbol"></i>
        <%= f.text_field :name, placeholder: 'Start typing here to create a task...', class: "col-xs-9" %>
        <%= f.submit 'Add task', class: "green-gradient col-xs-2" %>
      <% end %> 
  </div>
  <div class="task_wrapper">
    <%= render project.tasks.order('id') %>
  </div> 
</div>

app/views/projects/create.js.erb
new_project = $("<%= escape_javascript(render @project) %>").appendTo("#project-container");
new_project.hover(
    function () {
      $(this).find(".small-buttons").removeClass("hide");
    },
    function () {
      $(this).find(".small-buttons").addClass("hide");
    }
  );

new_project.find(".input_title").hide();
new_project.find(".edit-project").on('click', function(){
    $(this).parents('.project-header').find('.label_title').toggle();
    $(this).parents('.project-header').find('.input_title').toggle();
    
    return false;
  });

app/views/projects/destroy.js.erb
$('.delete-project').bind('ajax:success', function() {$(this).closest('.container').fadeOut()})

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div id="project-container">
    <%= render @projects %>
</div>

<br>
<div class="bottom-link" align="center">
  <%= link_to @project, method: :post, remote: true, id: "add-project", class: "btn btn-lg btn-primary blue-gradient shadow raised" do %>
    <i class="fa fa-plus"></i>
    Add TODO List
  <% end %>
</div>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/projects/update.js.erb
project_div = $("#project_<%= @project.id %>");
label = project_div.find('.label_title').toggle();
input = project_div.find('.input_title').toggle();
label[0].textContent = input[0].value;

app/views/tasks/_task.html.erb
<div class="row clearfix hover-colorize <%= task.completed? ? 'completed' : '' %>">
  <div class="complete col-xs-1">
    <%= link_to complete_project_task_path(task.project_id, task.id), remote: true, method: :patch, class: "complete-task" do%>
      <i class='fa <%= task.completed? ? 'fa-check-square-o' : 'fa-square-o' %>' ></i>
    <% end %>
  </div>
  <div class="task col-xs-9">
    <%= form_for( [task.project, task], remote: true ) do |f| %>
        <%= f.label "#{task.name}", class: 'task_label_title' %>
        <%= f.text_field :name, class: 'task_input_title' %>
    <% end %>
  </div>
  <div class="trash col-xs-2 hide">
    <i class="fa fa-sort"></i>
    |
    <%= link_to '', class: "edit-task" do %>
      <i class='fa fa-pencil'></i>
    <% end %>
    |
    <%= link_to project_task_path(task.project_id, task.id), method: :delete, data: { confirm: 'Are you sure?'}, class: 'delete-task', remote: true do %>
      <i class='fa fa-trash'></i>
    <% end %>
  </div>
</div>

app/views/tasks/complete.js.erb
$('.complete-task').bind('ajax:success', function() {
  $(this).closest('.row').addClass("completed");
  checkbox = $(this).find(".fa");
  checkbox.removeClass("fa-square-o");
  checkbox.addClass("fa-check-square-o");
});

app/views/tasks/create.js.erb
project_div = $("#project_<%= @project.id %>")
new_task = $("<%= escape_javascript(render @task) %>").appendTo(project_div.find(".task_wrapper"));
new_task.hover(
    function () {
      $(this).find(".trash").removeClass("hide");
    },
    function () {
      $(this).find(".trash").addClass("hide");
    }
  );

new_task.find(".task_input_title").hide();
new_task.find(".edit-task").on('click', function(){
    $(this).parents('.row').find('.task_label_title').toggle();
    $(this).parents('.row').find('.task_input_title').toggle();
    
    return false;
  });

project_div.find(".task-form #task_name")[0].value = "";

app/views/tasks/destroy.js.erb
$('.delete-task').bind('ajax:success', function() {$(this).closest('.row').fadeOut()})

app/views/tasks/update.js.erb
task_div = $("#edit_task_<%= @task.id %>");
label = task_div.find('.task_label_title').toggle();
input = task_div.find('.task_input_title').toggle();
label[0].textContent = input[0].value;